#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RevSDKMessageHandler.Resource", IsApplication=false)]

namespace RevSDKMessageHandler
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020030
			public static int ApplicationName = 2130837552;
			
			// aapt resource value: 0x7f02002f
			public static int Hello = 2130837551;
			
			// aapt resource value: 0x7f020000
			public static int accepted = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int app_name = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int bad_gateway = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int bad_request = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int conflict = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int continu = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int crash_toast_text = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int created = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int expectation_failed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int forbidden = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int found = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int g2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int g3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int g4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int gateway_timeout = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int gone = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int http_version_not_supported = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int internal_server_error = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int length_required = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int method_not_allowed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int moved_permanently = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int multiple_choices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int no_content = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int no_network = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int non_authoritative_information = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int not_acceptable = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int not_found = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int not_implemented = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int ok = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int payload_to_large = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int payment_required = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int permission_denied = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int read_phone_state = 2130837536;
			
			// aapt resource value: 0x7f020021
			public static int read_write_prmission = 2130837537;
			
			// aapt resource value: 0x7f020022
			public static int request_timeout = 2130837538;
			
			// aapt resource value: 0x7f020023
			public static int reset_content = 2130837539;
			
			// aapt resource value: 0x7f020024
			public static int see_other = 2130837540;
			
			// aapt resource value: 0x7f020025
			public static int service_unavailable = 2130837541;
			
			// aapt resource value: 0x7f020026
			public static int switching_protocols = 2130837542;
			
			// aapt resource value: 0x7f020027
			public static int temporary_redirect = 2130837543;
			
			// aapt resource value: 0x7f020028
			public static int undefined = 2130837544;
			
			// aapt resource value: 0x7f020029
			public static int unknown = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public static int unsupported_media_type = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public static int upgrade_required = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public static int uri_too_long = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public static int use_proxy = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public static int wifi = 2130837550;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
