#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Nuubit.SDK.Droid.Resource", IsApplication=false)]

namespace Nuubit.SDK.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public static int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public static int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public static int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030008
			public static int common_google_signin_btn_text_dark = 2130903048;
			
			// aapt resource value: 0x7f030000
			public static int common_google_signin_btn_text_dark_default = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int common_google_signin_btn_text_dark_disabled = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int common_google_signin_btn_text_dark_focused = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int common_google_signin_btn_text_dark_pressed = 2130903043;
			
			// aapt resource value: 0x7f030009
			public static int common_google_signin_btn_text_light = 2130903049;
			
			// aapt resource value: 0x7f030004
			public static int common_google_signin_btn_text_light_default = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int common_google_signin_btn_text_light_disabled = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int common_google_signin_btn_text_light_focused = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int common_google_signin_btn_text_light_pressed = 2130903047;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int common_google_signin_btn_text_light_pressed = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public static int adjust_height = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int adjust_width = 2131099649;
			
			// aapt resource value: 0x7f060006
			public static int auto = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int dark = 2131099655;
			
			// aapt resource value: 0x7f060003
			public static int icon_only = 2131099651;
			
			// aapt resource value: 0x7f060008
			public static int light = 2131099656;
			
			// aapt resource value: 0x7f060002
			public static int none = 2131099650;
			
			// aapt resource value: 0x7f060004
			public static int standard = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int wide = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public static int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04005b
			public static int ApplicationName = 2130968667;
			
			// aapt resource value: 0x7f04005a
			public static int Hello = 2130968666;
			
			// aapt resource value: 0x7f040011
			public static int accepted = 2130968593;
			
			// aapt resource value: 0x7f040012
			public static int app_name = 2130968594;
			
			// aapt resource value: 0x7f040013
			public static int bad_gateway = 2130968595;
			
			// aapt resource value: 0x7f040014
			public static int bad_request = 2130968596;
			
			// aapt resource value: 0x7f040000
			public static int common_google_play_services_enable_button = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int common_google_play_services_enable_text = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int common_google_play_services_enable_title = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int common_google_play_services_install_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int common_google_play_services_install_text = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int common_google_play_services_install_title = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int common_google_play_services_notification_ticker = 2130968582;
			
			// aapt resource value: 0x7f040010
			public static int common_google_play_services_unknown_issue = 2130968592;
			
			// aapt resource value: 0x7f040007
			public static int common_google_play_services_unsupported_text = 2130968583;
			
			// aapt resource value: 0x7f040008
			public static int common_google_play_services_update_button = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int common_google_play_services_update_text = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public static int common_google_play_services_update_title = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int common_google_play_services_updating_text = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public static int common_google_play_services_wear_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public static int common_open_on_phone = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public static int common_signin_button_text = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public static int common_signin_button_text_long = 2130968591;
			
			// aapt resource value: 0x7f040015
			public static int conflict = 2130968597;
			
			// aapt resource value: 0x7f040016
			public static int continu = 2130968598;
			
			// aapt resource value: 0x7f040017
			public static int crash_toast_text = 2130968599;
			
			// aapt resource value: 0x7f040018
			public static int created = 2130968600;
			
			// aapt resource value: 0x7f040019
			public static int critical = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public static int debug = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public static int details_of_loaded_sdk_configuration = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public static int error = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public static int expectation_failed = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public static int fail_init_sdk = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public static int failed_fetch_object = 2130968607;
			
			// aapt resource value: 0x7f040020
			public static int failed_refresh_configuration = 2130968608;
			
			// aapt resource value: 0x7f040021
			public static int failed_upload_stats = 2130968609;
			
			// aapt resource value: 0x7f040022
			public static int failure_all_lm = 2130968610;
			
			// aapt resource value: 0x7f040023
			public static int failure_monitoring_logic = 2130968611;
			
			// aapt resource value: 0x7f040024
			public static int forbidden = 2130968612;
			
			// aapt resource value: 0x7f040025
			public static int found = 2130968613;
			
			// aapt resource value: 0x7f040026
			public static int g2 = 2130968614;
			
			// aapt resource value: 0x7f040027
			public static int g3 = 2130968615;
			
			// aapt resource value: 0x7f040028
			public static int g4 = 2130968616;
			
			// aapt resource value: 0x7f040029
			public static int gateway_timeout = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public static int gone = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public static int http_version_not_supported = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public static int info = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public static int internal_server_error = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public static int length_required = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public static int method_not_allowed = 2130968623;
			
			// aapt resource value: 0x7f040030
			public static int moved_permanently = 2130968624;
			
			// aapt resource value: 0x7f040031
			public static int multiple_choices = 2130968625;
			
			// aapt resource value: 0x7f040032
			public static int network_error = 2130968626;
			
			// aapt resource value: 0x7f040033
			public static int no_content = 2130968627;
			
			// aapt resource value: 0x7f040034
			public static int no_network = 2130968628;
			
			// aapt resource value: 0x7f040035
			public static int non_authoritative_information = 2130968629;
			
			// aapt resource value: 0x7f040036
			public static int not_acceptable = 2130968630;
			
			// aapt resource value: 0x7f040037
			public static int not_found = 2130968631;
			
			// aapt resource value: 0x7f040038
			public static int not_implemented = 2130968632;
			
			// aapt resource value: 0x7f040039
			public static int ok = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public static int os_access_permissions = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public static int payload_to_large = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public static int payment_required = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public static int permission_denied = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public static int read_phone_state = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public static int read_write_prmission = 2130968639;
			
			// aapt resource value: 0x7f040040
			public static int received_object_with_5xx = 2130968640;
			
			// aapt resource value: 0x7f040041
			public static int recovable_oom = 2130968641;
			
			// aapt resource value: 0x7f040042
			public static int request_timeout = 2130968642;
			
			// aapt resource value: 0x7f040043
			public static int reset_content = 2130968643;
			
			// aapt resource value: 0x7f040044
			public static int sdk_initialization_ready_stage = 2130968644;
			
			// aapt resource value: 0x7f040045
			public static int see_other = 2130968645;
			
			// aapt resource value: 0x7f040046
			public static int service_unavailable = 2130968646;
			
			// aapt resource value: 0x7f040047
			public static int star_finish_sdk_stats_upload_process = 2130968647;
			
			// aapt resource value: 0x7f040048
			public static int start_finish_url_fetch = 2130968648;
			
			// aapt resource value: 0x7f040049
			public static int starting_ending_lm_selection_logic = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public static int starting_ending_sdk_configuration_refresh = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public static int switching_configuration_stale_mode = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public static int switching_operation_mode = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public static int switching_protocols = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public static int tcp_quic_connection_reestablishing = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public static int temporary_redirect = 2130968655;
			
			// aapt resource value: 0x7f040050
			public static int timing_performance_for_loaded_objects = 2130968656;
			
			// aapt resource value: 0x7f040051
			public static int undefined = 2130968657;
			
			// aapt resource value: 0x7f040052
			public static int unknown = 2130968658;
			
			// aapt resource value: 0x7f040053
			public static int unrecoverable_oom = 2130968659;
			
			// aapt resource value: 0x7f040054
			public static int unsupported_media_type = 2130968660;
			
			// aapt resource value: 0x7f040055
			public static int upgrade_required = 2130968661;
			
			// aapt resource value: 0x7f040056
			public static int uri_too_long = 2130968662;
			
			// aapt resource value: 0x7f040057
			public static int use_proxy = 2130968663;
			
			// aapt resource value: 0x7f040058
			public static int warning = 2130968664;
			
			// aapt resource value: 0x7f040059
			public static int wifi = 2130968665;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public static int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public static int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public static int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public static int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public static int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public static int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
